# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    env:
      VITE_ASSETS_BASEURL: https://evretifrasi-assets.netlify.app

    strategy:
      matrix:
        node-version: [22.x]
        

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - run: npm run build --if-present
    - run: npm test
    - name: Start deployment
      run: |
        npm i
        npm run build
        mv build /tmp
        cd /tmp
        git clone https://github.com/SavvasStephanides/savvas.git
        cd savvas
        rm -rf ./static/evretifrasi
        mv /tmp/build ./static/evretifrasi
        git status
        git config user.name "${GITHUB_ACTOR}"
        git config user.email "${GITHUB_ACTOR}@users.noreply.github.com"

        git add -A
        git commit -m "Automated Update Evre Ti Frasi"
        git push --all -f https://${{ secrets.GH_TOKEN }}@github.com/SavvasStephanides/savvas.git
